#!/usr/bin/env node
// Shared file discovery for language-independent bailiff checks.
// Default scan: git-tracked files plus harness dirs (.claude, .agent, .agents)
// even when those dirs are gitignored. Explicit path args bypass the default.
"use strict";

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const SKIP_DIR_NAMES = new Set([
  ".git",
  "node_modules",
  "vendor",
  "dist",
  "build",
  "coverage",
  "__pycache__",
  ".venv",
  "venv",
  "target",
  ".next",
  ".turbo",
  ".cache",
]);

const SKIP_EXT = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".svg",
  ".pdf", ".zip", ".gz", ".tgz", ".bz2", ".xz", ".7z", ".tar",
  ".woff", ".woff2", ".ttf", ".otf", ".eot",
  ".mp4", ".mp3", ".wav", ".mov", ".webm",
  ".wasm", ".so", ".dylib", ".dll", ".o", ".a", ".obj",
  ".class", ".jar", ".bin", ".exe", ".pyc", ".pyo",
  ".lock", ".map",
]);

const HARNESS_DIRS = [".claude", ".agent", ".agents"];
const MAX_BYTES = 1024 * 1024;

function isGenerated(content) {
  const head = content.slice(0, 1024);
  return /Code generated|AUTO-GENERATED|autogenerated|@generated/i.test(head);
}

function posix(p) {
  return p.split(path.sep).join("/");
}

function shouldSkipPath(relPath) {
  const parts = posix(relPath).split("/").filter(Boolean);
  if (parts.some((p) => SKIP_DIR_NAMES.has(p))) return true;
  const base = parts[parts.length - 1] || "";
  if (base === "package-lock.json" || base === "yarn.lock" || base === "pnpm-lock.yaml" || base === "go.sum" || base === "Cargo.lock") {
    return true;
  }
  if (/\.min\.(js|css)$/i.test(base)) return true;
  const ext = path.extname(base).toLowerCase();
  if (SKIP_EXT.has(ext)) return true;
  return false;
}

function isProbablyBinary(buf) {
  const n = Math.min(buf.length, 8192);
  for (let i = 0; i < n; i++) {
    if (buf[i] === 0) return true;
  }
  return false;
}

function gitLsFiles(root) {
  try {
    const out = execSync("git ls-files -z", {
      cwd: root,
      encoding: "buffer",
      maxBuffer: 32 * 1024 * 1024,
      stdio: ["ignore", "pipe", "ignore"],
    });
    return out
      .toString("utf8")
      .split("\0")
      .filter(Boolean);
  } catch (_e) {
    return null;
  }
}

function walkDir(absDir, root, acc) {
  let entries;
  try {
    entries = fs.readdirSync(absDir, { withFileTypes: true });
  } catch (_e) {
    return;
  }
  for (const ent of entries) {
    const abs = path.join(absDir, ent.name);
    const rel = posix(path.relative(root, abs));
    if (ent.isDirectory()) {
      if (SKIP_DIR_NAMES.has(ent.name)) continue;
      walkDir(abs, root, acc);
      continue;
    }
    if (!ent.isFile()) continue;
    if (shouldSkipPath(rel)) continue;
    acc.add(rel);
  }
}

function walkCwdFallback(root, acc) {
  let entries;
  try {
    entries = fs.readdirSync(root, { withFileTypes: true });
  } catch (_e) {
    return;
  }
  for (const ent of entries) {
    if (ent.name === ".git") continue;
    const abs = path.join(root, ent.name);
    if (ent.isDirectory()) {
      if (SKIP_DIR_NAMES.has(ent.name)) continue;
      walkDir(abs, root, acc);
    } else if (ent.isFile()) {
      const rel = posix(ent.name);
      if (!shouldSkipPath(rel)) acc.add(rel);
    }
  }
}

function addHarnessDirs(root, acc) {
  for (const name of HARNESS_DIRS) {
    const abs = path.join(root, name);
    if (!fs.existsSync(abs)) continue;
    const st = fs.statSync(abs);
    if (st.isDirectory()) walkDir(abs, root, acc);
    else if (st.isFile()) acc.add(name);
  }
}

function expandArg(root, arg, acc) {
  const abs = path.isAbsolute(arg) ? arg : path.resolve(root, arg);
  if (!fs.existsSync(abs)) return;
  const st = fs.statSync(abs);
  if (st.isDirectory()) {
    walkDir(abs, root, acc);
    return;
  }
  if (st.isFile()) {
    acc.add(posix(path.relative(root, abs)) || posix(arg));
  }
}

function readableText(root, rel) {
  const abs = path.resolve(root, rel);
  let st;
  try {
    st = fs.statSync(abs);
  } catch (_e) {
    return null;
  }
  if (!st.isFile() || st.size === 0 || st.size > MAX_BYTES) return null;
  let buf;
  try {
    buf = fs.readFileSync(abs);
  } catch (_e) {
    return null;
  }
  if (isProbablyBinary(buf)) return null;
  return buf.toString("utf8");
}

/**
 * Collect files to scan.
 * @param {string[]} args process.argv.slice(2)
 * @param {{root?: string, skipPath?: (rel: string) => boolean}} [opts]
 * @returns {{root: string, files: string[]}} relative paths
 */
function collectFiles(args, opts) {
  const root = (opts && opts.root) || process.cwd();
  const extraSkip = (opts && opts.skipPath) || (() => false);
  const acc = new Set();
  if (args && args.length > 0) {
    for (const a of args) expandArg(root, a, acc);
  } else {
    const tracked = gitLsFiles(root);
    if (tracked) {
      for (const f of tracked) {
        if (!shouldSkipPath(f)) acc.add(f);
      }
    } else {
      walkCwdFallback(root, acc);
    }
    addHarnessDirs(root, acc);
  }
  const files = [];
  for (const rel of acc) {
    if (extraSkip(rel) || shouldSkipPath(rel)) continue;
    if (readableText(root, rel) === null) continue;
    files.push(rel);
  }
  files.sort();
  return { root, files };
}

function readLines(root, rel) {
  const content = readableText(root, rel);
  if (content === null) return null;
  return { content, lines: content.split("\n") };
}

function emit(findings) {
  let has = false;
  for (const f of findings) {
    has = true;
    process.stdout.write(JSON.stringify(f) + "\n");
  }
  process.exit(has ? 1 : 0);
}

function finding(file, line, severity, check, message, code) {
  return { file, line, severity, check, message, code };
}

module.exports = {
  HARNESS_DIRS,
  collectFiles,
  emit,
  finding,
  isGenerated,
  posix,
  readLines,
  readableText,
  shouldSkipPath,
};
